<?php

class Autoloader
{
    public function generate(string $vendorDir): void
    {
        $packages = [];

        // Scan vendor/ for packages with package.json
        foreach (glob($vendorDir . '/*', GLOB_ONLYDIR) as $pkgDir) {
            $name = basename($pkgDir);
            $pkgJson = "$pkgDir/package.json";
            $info = [];
            if (file_exists($pkgJson)) {
                $info = json_decode(file_get_contents($pkgJson), true) ?: [];
            }
            $packages[$name] = [
                'dir'     => $pkgDir,
                'version' => $info['version'] ?? '?',
                'main'    => $info['main'] ?? 'index.php',
            ];
        }

        // Generate autoloader
        $namespaceMap = [];
        foreach ($packages as $name => $pkg) {
            $ns = 'pakit\\' . $name;
            $namespaceMap[$ns] = $pkg['dir'];
        }

        $code = "<?php\n\n";
        $code .= "// Generated by pak-it autoloader\n";
        $code .= "// Packages: " . count($packages) . "\n\n";
        $code .= "spl_autoload_register(function (\$class) {\n";
        $code .= "    \$map = [\n";
        foreach ($namespaceMap as $ns => $dir) {
            $code .= "        " . var_export($ns . '\\', true) . " => " . var_export($dir . '/', true) . ",\n";
        }
        $code .= "    ];\n";
        $code .= "    foreach (\$map as \$prefix => \$baseDir) {\n";
        $code .= "        if (strncmp(\$prefix, \$class, strlen(\$prefix)) === 0) {\n";
        $code .= "            \$relative = substr(\$class, strlen(\$prefix));\n";
        $code .= "            \$file = \$baseDir . str_replace('\\\\', '/', \$relative) . '.php';\n";
        $code .= "            if (file_exists(\$file)) { require \$file; return; }\n";
        $code .= "        }\n";
        $code .= "    }\n";
        $code .= "});\n";
        $code .= "\n";
        $code .= "// Package registry\n";
        $code .= "return " . var_export($packages, true) . ";\n";

        file_put_contents($vendorDir . '/autoload.php', $code);
        echo "    Autoloader generated: " . count($packages) . " packages registered\n";
    }
}
